docfx/docfx.json
docfx/docs/custom-converters.md
docfx/docs/customizing-serialization.md
docfx/docs/performance.md
docfx/docs/toc.yml
src/Nerdbank.MessagePack/MessagePackSerializer.cs

Also add lots of docs around customizing serialization.

Enable registering custom converters

---

docfx/docs/custom-converters.md
src/Nerdbank.MessagePack/MessagePackSerializer.cs
src/Nerdbank.MessagePack/SerializationContext.cs
test/Nerdbank.MessagePack.Tests/CustomConverterTests.cs
test/Nerdbank.MessagePack.Tests/SerializationContextTests.cs

Provide custom converters a means to delegate sub-values

---

docfx/docs/customizing-serialization.md
src/Nerdbank.MessagePack/MessagePackNamingPolicy.cs
src/Nerdbank.MessagePack/MessagePackSerializer.cs
src/Nerdbank.MessagePack/StandardVisitor.cs
test/Nerdbank.MessagePack.Tests/CamelCaseNamingPolicyTests.cs
test/Nerdbank.MessagePack.Tests/NamingPolicyApplicationTests.cs
test/Nerdbank.MessagePack.Tests/PascalCaseNamingPolicyTests.cs

Offer camelCase property name transformation

---

Directory.Packages.props
src/Nerdbank.MessagePack/StandardVisitor.cs
test/Nerdbank.MessagePack.Tests/Nerdbank.MessagePack.Tests.csproj
test/Nerdbank.MessagePack.Tests/SharedTestCases.cs

- Switch dependency from `typeshape-csharp` to `PolyType`
- Added exhaustive test cases
- Fix stack overflow

Add exhaustive test cases and fix stack overflow

---

src/Nerdbank.MessagePack/Converters/CommonRecords.cs
src/Nerdbank.MessagePack/StandardVisitor.cs
test/Nerdbank.MessagePack.Tests/MessagePackSerializerTests.cs

Avoid serializing properties that cannot be deserialized

---

src/Nerdbank.MessagePack/Converters/RawMessagePackConverter.cs
src/Nerdbank.MessagePack/MessagePackAsyncWriter.cs
src/Nerdbank.MessagePack/MessagePackReader.cs
src/Nerdbank.MessagePack/PublicAPI.Unshipped.txt
src/Nerdbank.MessagePack/RawMessagePack.cs
test/Nerdbank.MessagePack.Tests/RawMessagePackTests.cs

Add `RawMessagePack` struct for deferred deserialization

---

global.json
tools/Install-NuGetCredProvider.ps1

Merge latest Library.Template

---

Directory.Packages.props
src/Nerdbank.MessagePack/ReferencePreservingVisitor.cs
src/Nerdbank.MessagePack/SecureHash/ByValueVisitor.cs
src/Nerdbank.MessagePack/SecureHash/SecureVisitor.cs
src/Nerdbank.MessagePack/StandardVisitor.cs
test/Nerdbank.MessagePack.Tests/MessagePackSerializerTests.cs

Bump PolyType to 0.17.1

---

Nerdbank.MessagePack.sln
docfx/docs/custom-converters.md
docfx/docs/customizing-serialization.md
docfx/docs/features.md
docfx/docs/getting-started.md
docfx/docs/performance.md
docfx/docs/security.md
docfx/docs/toc.yml
docfx/docs/type-shapes.md
docfx/docs/unions.md
samples/.editorconfig
samples/CustomConverters.cs
samples/CustomizingSerialization.cs
samples/GettingStarted.cs
samples/Samples.csproj
samples/Security.cs
samples/TypeShapePatterns.cs
samples/Unions.cs
samples/Usings.cs
src/Nerdbank.MessagePack/MessagePackSerializer.cs
src/Nerdbank.MessagePack/PublicAPI.Unshipped.txt
src/Nerdbank.MessagePack/README.md
test/Nerdbank.MessagePack.Tests/ReflectionShapeProviderTests.cs

Migrate a bunch of code samples into compileable files to ensure they are valid.

Lots of docs work

---

src/Nerdbank.MessagePack/MessagePackSerializer.AutomatedFriendlyOverloads.cs
src/Nerdbank.MessagePack/MessagePackSerializer.AutomatedFriendlyOverloads.tt
src/Nerdbank.MessagePack/MessagePackSerializer.FriendlyOverloads.cs
src/Nerdbank.MessagePack/MessagePackSerializer.cs
src/Nerdbank.MessagePack/Nerdbank.MessagePack.csproj
src/Nerdbank.MessagePack/PublicAPI.Unshipped.txt
src/Nerdbank.MessagePack/StreamBufferWriter.cs
test/Nerdbank.MessagePack.Tests/StreamTests.cs
test/Nerdbank.MessagePack.Tests/Usings.cs

Add Stream overloads for Serialize/Deserialize

---

src/Nerdbank.MessagePack/MessagePackPrimitives.Writers.cs

It turns out that indexing into span, and using `MemoryMarshal.Write`, results in significantly more compiled assembly code and slower perf.

Speed up `MessagePackPrimitives` writers by using `ref byte`

---

src/Nerdbank.MessagePack.Analyzers/ConverterAnalyzers.cs
src/Nerdbank.MessagePack.Analyzers/ReferenceSymbols.cs
src/Nerdbank.MessagePack/Converters/ArrayWithNestedDimensionsConverter`2.cs
src/Nerdbank.MessagePack/Converters/DictionaryConverter`3.cs
src/Nerdbank.MessagePack/Converters/EnumerableConverter`2.cs
src/Nerdbank.MessagePack/Converters/ObjectArrayConverter`1.cs
src/Nerdbank.MessagePack/Converters/ObjectMapConverter`1.cs
src/Nerdbank.MessagePack/Converters/SubTypeUnionConverter`1.cs
src/Nerdbank.MessagePack/IMessagePackConverter.cs
src/Nerdbank.MessagePack/MessagePackConverter`1.cs
src/Nerdbank.MessagePack/Nerdbank.MessagePack.csproj
src/Nerdbank.MessagePack/ReferencePreservingConverter`1.cs
test/Nerdbank.MessagePack.Analyzers.Tests/ConverterAnalyzersTests.cs

This ended up finding a bunch of issues with the NBMsgPack031 analyzer, most of which are fixed and the rest are suppressed.

Run analyzers on main library

---

.github/workflows/build.yml
docfx/analyzers/NBMsgPack033.md
docfx/analyzers/NBMsgPack034.md
docfx/analyzers/NBMsgPack035.md
docfx/analyzers/NBMsgPack036.md
docfx/analyzers/NBMsgPack037.md
docfx/analyzers/index.md
docfx/analyzers/toc.yml
samples/.editorconfig
samples/AnalyzerDocs/NBMsgPack033.cs
samples/AnalyzerDocs/NBMsgPack034.cs
samples/AnalyzerDocs/NBMsgPack035.cs
samples/AnalyzerDocs/NBMsgPack036.cs
samples/AnalyzerDocs/NBMsgPack037.cs
samples/CustomConverters.cs
src/Analyzers.props
src/Nerdbank.MessagePack.Analyzers/AnalyzerReleases.Unshipped.md
src/Nerdbank.MessagePack.Analyzers/ConverterAnalyzers.cs
src/Nerdbank.MessagePack.Analyzers/Strings.resx
src/Nerdbank.MessagePack/Converters/ArrayConverter`1.cs
src/Nerdbank.MessagePack/Converters/DictionaryConverter`3.cs
src/Nerdbank.MessagePack/Converters/ObjectArrayConverter`1.cs
src/Nerdbank.MessagePack/Converters/ObjectMapConverter`1.cs
src/Nerdbank.MessagePack/Converters/ObjectMapWithNonDefaultCtorConverter`2.cs
test/Nerdbank.MessagePack.Analyzers.Tests/ConverterAnalyzersTests.cs
test/Nerdbank.MessagePack.Analyzers.Tests/Verifiers/CodeFixVerifier`2.cs

These analyzers work together to help ensure correct definitions of async-supporting MessagePackConverters.

Add NBMsgPack033 - NBMsgPack037 analyzers

---

docfx/analyzers/NBMsgPack106.md
docfx/analyzers/index.md
docfx/analyzers/toc.yml
src/Nerdbank.MessagePack.Analyzers.CodeFixes/MigrationCodeFix.cs
src/Nerdbank.MessagePack.Analyzers/AnalyzerReleases.Unshipped.md
src/Nerdbank.MessagePack.Analyzers/MessagePackCSharpReferenceSymbols.cs
src/Nerdbank.MessagePack.Analyzers/MigrationAnalyzer.cs
src/Nerdbank.MessagePack.Analyzers/Strings.resx
test/Nerdbank.MessagePack.Analyzers.Tests/MigrationAnalyzerTests.cs

Add SerializationConstructorAttribute migration analyzer

---

src/Nerdbank.MessagePack/Converters/BclConverters.cs
src/Nerdbank.MessagePack/StandardVisitor.cs
test/Nerdbank.MessagePack.Tests/PrimitiveConverterTests.cs

Add converter for `System.Drawing.Color`

---

src/Nerdbank.MessagePack.Analyzers/ConverterAnalyzers.cs
src/Nerdbank.MessagePack.Analyzers/Strings.resx
src/Nerdbank.MessagePack/Converters/SubTypeUnionConverter`1.cs
test/Nerdbank.MessagePack.Analyzers.Tests/ConverterAnalyzersTests.cs

[Enhance converter analyzers to catch more async errors](https://github.com/AArnott/Nerdbank.MessagePack/commit/4d3331f3b18526fb55d149173114d8396c4b7e60)

Better async analyzers

---

docfx/docs/custom-converters.md
samples/CustomConverters.cs
src/Nerdbank.MessagePack/MessagePackReader.cs
src/Nerdbank.MessagePack/MessagePackString.cs
src/Nerdbank.MessagePack/net8.0/PublicAPI.Unshipped.txt
src/Nerdbank.MessagePack/netstandard2.0/PublicAPI.Unshipped.txt
test/Nerdbank.MessagePack.Tests/MessagePackReaderTests.cs
test/Nerdbank.MessagePack.Tests/MessagePackStringTests.cs

This helps authors of custom converters to reduce string allocation and encoding costs.
Closes #183

Add MessagePackString class

---

docfx/docs/custom-converters.md
docfx/docs/migrating.md
samples/CustomConverters.cs
src/Nerdbank.MessagePack/ConverterCache.cs
src/Nerdbank.MessagePack/JsonSchemaContext.cs
src/Nerdbank.MessagePack/MessagePackSerializer.GetSchema.cs
src/Nerdbank.MessagePack/MessagePackSerializer.cs
src/Nerdbank.MessagePack/MultiDimensionalArrayFormat.cs
src/Nerdbank.MessagePack/SerializationContext.cs
src/Nerdbank.MessagePack/StandardVisitor.cs
src/Nerdbank.MessagePack/net8.0/PublicAPI.Unshipped.txt
src/Nerdbank.MessagePack/netstandard2.0/PublicAPI.Unshipped.txt
test/Nerdbank.MessagePack.Tests/CustomConverterTests.cs
test/Nerdbank.MessagePack.Tests/MessagePackSerializerTests.cs
test/Nerdbank.MessagePack.Tests/SerializationContextTests.cs

Add support for stateful converters via `SerializationContext`

---

docfx/docs/custom-converters.md
samples/ApplyingSerializationContext.cs
samples/CustomConverters.cs
src/Nerdbank.MessagePack/SerializationContext.cs

Document pattern for modifying state

---

src/Nerdbank.MessagePack/Converters/CommonRecords.cs
src/Nerdbank.MessagePack/StandardVisitor.cs
test/Nerdbank.MessagePack.Tests/MessagePackSerializerTests.cs

Gracefully handle ctor parameters named by the serialized name

---

.github/workflows/build.yml
docfx/analyzers/NBMsgPack051.md
docfx/analyzers/index.md
docfx/analyzers/toc.yml
samples/AnalyzerDocs/NBMsgPack051.cs
src/Nerdbank.MessagePack.Analyzers/AnalyzerReleases.Unshipped.md
src/Nerdbank.MessagePack.Analyzers/Constants.cs
src/Nerdbank.MessagePack.Analyzers/DotNetApiUsageAnalyzer.cs
src/Nerdbank.MessagePack.Analyzers/Strings.resx
src/Nerdbank.MessagePack/KnownSubTypeAttribute.cs
src/Nerdbank.MessagePack/PreferDotNetAlternativeApiAttribute.cs
test/Nerdbank.MessagePack.Analyzers.Tests/DotNetApiUsageAnalyzerTests.cs

Add NBMsgPack051 analyzer

---

src/Nerdbank.MessagePack/MessagePackSerializer.cs
src/Nerdbank.MessagePack/ReferenceEqualityTracker.cs
src/Nerdbank.MessagePack/ReferencePreservingConverter`1.cs
test/Nerdbank.MessagePack.Tests/ReferencePreservationTests.cs
test/Nerdbank.MessagePack.Tests/StreamingEnumerableTests.cs

Add async converter support to the reference preserving wrapper

---

src/Nerdbank.MessagePack.Analyzers.CodeFixes/MigrationCodeFix.cs
test/Nerdbank.MessagePack.Analyzers.Tests/ConverterAnalyzersTests.cs
test/Nerdbank.MessagePack.Analyzers.Tests/KeyAttributeUseAnalyzerTests.cs
test/Nerdbank.MessagePack.Analyzers.Tests/MigrationAnalyzerTests.cs
test/Nerdbank.MessagePack.Analyzers.Tests/Nerdbank.MessagePack.Analyzers.Tests.csproj
test/Nerdbank.MessagePack.Analyzers.Tests/Verifiers/CodeFixVerifier`2.cs

This also gets the PolyType source generator to run as part of the analyzer tests.
Fixes #82

Activate and fix last Migration code fix test

---

src/Nerdbank.MessagePack/Utilities/BufferWriterExtensions.cs

This is as suggested by @clivetong in https://github.com/MessagePack-CSharp/MessagePack-CSharp/issues/2171

Add memory size check to GetMemoryCheckResult

---

docfx/analyzers/NBMsgPack051.md
samples/AnalyzerDocs/NBMsgPack051.cs
samples/TypeShapePatterns.cs
src/Nerdbank.MessagePack.Analyzers/DotNetApiUsageAnalyzer.cs
src/Nerdbank.MessagePack/MessagePackSerializer.AutomatedFriendlyOverloads.cs
src/Nerdbank.MessagePack/MessagePackSerializer.AutomatedFriendlyOverloads.tt
src/Nerdbank.MessagePack/MessagePackSerializer.FriendlyOverloads.cs
src/Nerdbank.MessagePack/MessagePackSerializer.cs
test/Nerdbank.MessagePack.Analyzers.Tests/DotNetApiUsageAnalyzerTests.cs
test/Nerdbank.MessagePack.Tests/Nerdbank.MessagePack.Tests.csproj

Hide and discourage use of more unprotected APIs when targeting .NET

Hide and discourage use of more unprotected APIs when targeting .NET

---

src/Nerdbank.MessagePack/ConverterCache.cs
src/Nerdbank.MessagePack/MessagePackSerializer.cs
src/Nerdbank.MessagePack/StandardVisitor.cs
test/Nerdbank.MessagePack.Tests/PerfOverSchemaStabilityTests.cs

Add `MessagePackSerializer.PerfOverSchemaStability` property

---

docfx/docs/migrating.md
src/Nerdbank.MessagePack/ConverterCache.cs
src/Nerdbank.MessagePack/Converters/ObjectArrayConverter`1.cs
src/Nerdbank.MessagePack/Converters/ObjectMapConverter`1.cs
src/Nerdbank.MessagePack/Converters/PrimitiveConverterLookup.cs
src/Nerdbank.MessagePack/MessagePackSerializer.GetSchema.cs
src/Nerdbank.MessagePack/MessagePackSerializer.cs
src/Nerdbank.MessagePack/ReferenceEqualityTracker.cs
src/Nerdbank.MessagePack/ReferencePreservationMode.cs
src/Nerdbank.MessagePack/SerializationContext.cs
src/Nerdbank.MessagePack/StandardVisitor.cs
test/Nerdbank.MessagePack.Tests/MessagePackSerializerTests.cs
test/Nerdbank.MessagePack.Tests/ReferencePreservationTests.cs
test/Nerdbank.MessagePack.Tests/SchemaTests.cs
test/Nerdbank.MessagePack.Tests/SharedTestCases.cs
test/Nerdbank.MessagePack.Tests/StreamingEnumerableTests.cs
test/Nerdbank.MessagePack.Tests/SurrogateTests.cs

Add support for reference cycles

---

docfx/docs/custom-converters.md
samples/cs/CustomConverters.cs
src/Nerdbank.MessagePack/ConverterCache.cs
src/Nerdbank.MessagePack/IMessagePackConverterFactory.cs
src/Nerdbank.MessagePack/MessagePackSerializer.cs
test/Nerdbank.MessagePack.Tests/CustomConverterFactoryTests.cs

Add `MessagePackSerializer.RegisterConverterFactory`

---

docfx/docs/built-in-converters.md
docfx/docs/toc.yml
src/Nerdbank.MessagePack/Converters/JsonDocumentConverter.cs
src/Nerdbank.MessagePack/Converters/JsonElementConverter.cs
src/Nerdbank.MessagePack/Converters/JsonNodeConverter.cs
src/Nerdbank.MessagePack/Converters/PrimitiveConverterLookup.cs
src/Nerdbank.MessagePack/Converters/PrimitiveConverterLookup.tt
test/Nerdbank.MessagePack.Tests/Converters/JsonDocumentConverterTests.cs
test/Nerdbank.MessagePack.Tests/Converters/JsonElementConverterTests.cs
test/Nerdbank.MessagePack.Tests/Converters/JsonNodeConverterTests.cs
test/Nerdbank.MessagePack.Tests/MessagePackSerializerTestBase.cs
test/Nerdbank.MessagePack.Tests/MessagePackSerializerTests.cs
test/Nerdbank.MessagePack.Tests/ReflectionShapeProviderTests.cs
test/Nerdbank.MessagePack.Tests/SharedTestCases.cs
test/Nerdbank.MessagePack.Tests/StreamingEnumerableTests.cs

Add converters for System.Text.Json types

---

src/Nerdbank.MessagePack/Converters/MessagePackValueConverter.cs
src/Nerdbank.MessagePack/Converters/PrimitiveConverterLookup.cs
src/Nerdbank.MessagePack/Converters/PrimitiveConverterLookup.tt
src/Nerdbank.MessagePack/MessagePackValue.cs
src/Nerdbank.MessagePack/MessagePackValueKind.cs
test/Nerdbank.MessagePack.Tests/Converters/MessagePackValueConverterTests.cs
test/Nerdbank.MessagePack.Tests/MessagePackSerializerPolyfill.cs
test/Nerdbank.MessagePack.Tests/MessagePackValueTests.cs

I don't know yet whether this will be useful.

Add `MessagePackValue` variant struct and converter

---

Directory.Packages.props

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

Merge the latest Library.Template

---

.github/workflows/build.yml
Nerdbank.MessagePack.slnx
src/Nerdbank.MessagePack/Converters/UnionConverter`1.cs
test/AotCompatibilityTest/AotCompatibilityTest.csproj
test/AotCompatibilityTest/Program.cs
test/dirs.proj

This turns on a more comprehensive scan of our trim-readiness, and fixes the only issue it found.

Fix small trim readiness issue

---

src/Nerdbank.MessagePack/Extension.cs
src/Nerdbank.MessagePack/IStructuralSecureEqualityComparer`1.cs
src/Nerdbank.MessagePack/MessagePackValue.cs
src/Nerdbank.MessagePack/SecureHash/SecureCustomEqualityComparer`1.cs
src/Nerdbank.MessagePack/SecureHash/SecureVisitor.cs
src/Nerdbank.MessagePack/SecureHash/StructuralCustomEqualityComparer`1.cs
src/Nerdbank.MessagePack/SecureHash/StructuralVisitor.cs
src/Nerdbank.MessagePack/StructuralEqualityComparer.cs
test/Nerdbank.MessagePack.Tests/ExtensionTests.cs
test/Nerdbank.MessagePack.Tests/MessagePackSerializerTestBase.cs
test/Nerdbank.MessagePack.Tests/MessagePackValueTests.cs
test/Nerdbank.MessagePack.Tests/StructuralEqualityComparerTests.cs

Rename "Deep" to "Structural" in public API

---

Directory.Packages.props

Update PolyTypeVersion to 0.48.1

---

Directory.Packages.props
Nerdbank.MessagePack.slnx
docfx/docfx.json
docfx/docs/aspnetmvc.md
docfx/docs/toc.yml
samples/AspNetMvc/AspNetMvc.csproj
samples/AspNetMvc/Program.cs
src/Nerdbank.MessagePack.AspNetCoreMvcFormatter/MessagePackInputFormatter.cs
src/Nerdbank.MessagePack.AspNetCoreMvcFormatter/MessagePackOutputFormatter.cs
src/Nerdbank.MessagePack.AspNetCoreMvcFormatter/Nerdbank.MessagePack.AspNetCoreMvcFormatter.csproj
src/Nerdbank.MessagePack/MessagePackSerializer.cs
test/Nerdbank.MessagePack.AspNetCoreMvcFormatter.Tests/AspNetCoreMvcFormatterTest.cs
test/Nerdbank.MessagePack.AspNetCoreMvcFormatter.Tests/Nerdbank.MessagePack.AspNetCoreMvcFormatter.Tests.csproj
test/Nerdbank.MessagePack.AspNetCoreMvcFormatter.Tests/Polyfills.cs
test/Nerdbank.MessagePack.AspNetCoreMvcFormatter.Tests/User.cs
test/dirs.proj

Add ASP.NET MVC formatter package

---

src/Nerdbank.MessagePack/Utilities/SpanDictionary.cs
test/Nerdbank.MessagePack.Tests/ObjectsAsMapTests.cs

Fix `IndexOutOfRangeException` thrown from `SpanDictionary.TryGetValue`

---

src/Nerdbank.MessagePack/SecureHash/SecureUnionEqualityComparer`1.cs
src/Nerdbank.MessagePack/SecureHash/SecureVisitor.cs
src/Nerdbank.MessagePack/SecureHash/StructuralUnionEqualityComparer`1.cs
src/Nerdbank.MessagePack/SecureHash/StructuralVisitor.cs
test/Nerdbank.MessagePack.Tests/StructuralEqualityComparerTests.cs

- Support comparing objects w/o properties if they are part of a type union
- Generate unique hash codes based on union case index

Improve structural comparison of union types

---

.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/prepare-release.yml
.github/workflows/release.yml

These changes should help to improve the score given by https://github.com/ossf/scorecard

Scorecard work

---

src/Nerdbank.MessagePack/MessagePackSerializer.FriendlyOverloads.cs
test/Nerdbank.MessagePack.Tests/MessagePackSerializerTests.cs

Add more `Object` overloads of serialize and deserialize methods
