README.md, doc/unions.md, src/Nerdbank.MessagePack/Converters/ArrayConverter`1.cs, src/Nerdbank.MessagePack/Converters/ArrayWithFlattenedDimensionsConverter`2.cs, src/Nerdbank.MessagePack/Converters/ArrayWithNestedDimensionsConverter`2.cs, src/Nerdbank.MessagePack/Converters/CommonRecords.cs, src/Nerdbank.MessagePack/Converters/DelayedConverter`1.cs, src/Nerdbank.MessagePack/Converters/DictionaryConverter`3.cs, src/Nerdbank.MessagePack/Converters/EnumAsOrdinalConverter`2.cs, src/Nerdbank.MessagePack/Converters/EnumerableConverter`2.cs, src/Nerdbank.MessagePack/Converters/IntConverters.cs, src/Nerdbank.MessagePack/Converters/IntConverters.tt, src/Nerdbank.MessagePack/Converters/ObjectArrayConverter`1.cs, src/Nerdbank.MessagePack/Converters/ObjectArrayWithNonDefaultCtorConverter`2.cs, src/Nerdbank.MessagePack/Converters/ObjectMapConverter`1.cs, src/Nerdbank.MessagePack/Converters/ObjectMapWithNonDefaultCtorConverter`2.cs, src/Nerdbank.MessagePack/Converters/PrimitiveConverters.cs, src/Nerdbank.MessagePack/Converters/SubTypeUnionConverter`1.cs, src/Nerdbank.MessagePack/IMessagePackConverter.cs, src/Nerdbank.MessagePack/KnownSubTypeAttribute.cs, src/Nerdbank.MessagePack/MessagePackConverter`1.cs, src/Nerdbank.MessagePack/MessagePackSerializer.cs, src/Nerdbank.MessagePack/README.md, src/Nerdbank.MessagePack/StandardVisitor.cs, test/Nerdbank.MessagePack.Tests/KnownSubTypeTests.cs, test/Nerdbank.MessagePack.Tests/MessagePackSerializerTestBase.cs
This adds `UnionAttribute`, which can be applied to a type declaration to allow derivative types to appear at runtime where the base type is the declared type. In such a case, the data provided by the attribute dictates how the derived type will be identified in the serialized stream.
=> Add support for polymorphic serialization

src/Nerdbank.MessagePack/MessagePackSerializer.cs, src/Nerdbank.MessagePack/StandardVisitor.cs, test/Nerdbank.MessagePack.Tests/KnownSubTypeTests.cs
Fixes [the bug @eiriktsarpalis predicted](https://github.com/AArnott/Nerdbank.MessagePack/pull/5#discussion_r1825721992).
=> Fix `InvalidCastException` when union subtypes implement `IEnumerable`

src/Nerdbank.MessagePack/BufferWriter.cs, test/Nerdbank.MessagePack.Tests/MessagePackSerializerTests.cs
API change and new test addition.
Refactored `BufferWriter` API and added new serialization test.
- `BufferWriter.cs`: Changed several methods and properties from public to internal, removed `bytesCommitted` and `UnderlyingWriter`.
- `MessagePackSerializerTests.cs`: Added `NoProperties` test method and `EmptyClass` for roundtrip serialization testing.
=> Simplify `BufferWriter` and add test

src/.editorconfig, src/Nerdbank.MessagePack/BufferMemoryWriter.cs, src/Nerdbank.MessagePack/BufferWriter.cs, src/Nerdbank.MessagePack/Converters/ArrayConverter`1.cs, src/Nerdbank.MessagePack/Converters/CommonRecords.cs, src/Nerdbank.MessagePack/Converters/ObjectArrayConverter`1.cs, src/Nerdbank.MessagePack/Converters/ObjectArrayWithNonDefaultCtorConverter`2.cs, src/Nerdbank.MessagePack/Converters/ObjectMapConverter`1.cs, src/Nerdbank.MessagePack/Converters/ObjectMapWithNonDefaultCtorConverter`2.cs, src/Nerdbank.MessagePack/MessagePackAsyncReader.cs, src/Nerdbank.MessagePack/MessagePackAsyncWriter.cs, src/Nerdbank.MessagePack/MessagePackConverter`1.cs, src/Nerdbank.MessagePack/MessagePackSerializer.cs, src/Nerdbank.MessagePack/Nerdbank.MessagePack.csproj, src/Nerdbank.MessagePack/SerializationContext.cs, src/Nerdbank.MessagePack/StandardVisitor.cs, test/Benchmarks/SyncVsAsyncArrays.cs, test/Benchmarks/SyncVsAsyncPoco.cs, test/Nerdbank.MessagePack.Tests/AsyncSerializationTests.cs, test/Nerdbank.MessagePack.Tests/MessagePackSerializerTestBase.cs
The mechanics of how it works is protected by `[Experimental]` attributes since it may be up for massive changes as we learn how to do this in a performant and usable way for Converter authors.
 
Perf comparisons have some really disappointing surprises but also some encouraging numbers.
| Method            | Mean      | Error    | StdDev   |
|------------------ |----------:|---------:|---------:|
| Sync_Serialize    |  72.25 μs | 0.146 μs | 0.129 μs |
| Sync_Deserialize  |  43.20 μs | 0.201 μs | 0.178 μs |
| Async_Serialize   | 209.77 μs | 0.597 μs | 0.559 μs |
| Async_Deserialize |  45.01 μs | 0.223 μs | 0.208 μs |
| Method            | Mean       | Error   | StdDev  |
|------------------ |-----------:|--------:|--------:|
| Sync_Serialize    |   168.6 ns | 0.79 ns | 0.74 ns |
| …
=> Add support for async (de)serialization

docfx/docs/custom-converters.md, docfx/docs/security.md, src/Nerdbank.MessagePack/Converters/DictionaryConverter`3.cs, src/Nerdbank.MessagePack/Converters/EnumerableConverter`2.cs, src/Nerdbank.MessagePack/IDeserializeInto`1.cs, src/Nerdbank.MessagePack/StandardVisitor.cs, test/Nerdbank.MessagePack.Tests/SecurityTests.cs
This provides an opportunity for the user to apply a collision resistant hash function for keyed collections, even while TypeShape does not yet support creating such collections automatically.
=> Add support for inflating pre-created collections in the deserializer

docfx/analyzers/NBMsgPack020.md, docfx/analyzers/NBMsgPack021.md, docfx/analyzers/index.md, docfx/analyzers/toc.yml, src/Nerdbank.MessagePack.Analyzers/AnalyzerReleases.Unshipped.md, src/Nerdbank.MessagePack.Analyzers/AnalyzerUtilities.cs, src/Nerdbank.MessagePack.Analyzers/KnownSubTypeAnalyzers.cs, src/Nerdbank.MessagePack.Analyzers/MessagePackConverterAttributeAnalyzer.cs, src/Nerdbank.MessagePack.Analyzers/ReferenceSymbols.cs, src/Nerdbank.MessagePack.Analyzers/Strings.resx, src/Nerdbank.MessagePack/MessagePackConverterAttribute.cs, src/Nerdbank.MessagePack/StandardVisitor.cs, test/Nerdbank.MessagePack.Analyzers.Tests/MessagePackConverterAttributeAnalyzerTests.cs, test/Nerdbank.MessagePack.Tests/MessagePackConverterAttributeTests.cs
This comes with two new analyzers.
Closes #38
=> Add `MessagePackConverterAttribute` to prescribe default custom converters for custom types

docfx/analyzers/NBMsgPack030.md, docfx/analyzers/NBMsgPack031.md, docfx/analyzers/index.md, docfx/analyzers/toc.yml, src/Nerdbank.MessagePack.Analyzers/AnalyzerReleases.Unshipped.md, src/Nerdbank.MessagePack.Analyzers/ConverterAnalyzers.cs, src/Nerdbank.MessagePack.Analyzers/ReferenceSymbols.cs, src/Nerdbank.MessagePack.Analyzers/Strings.resx, test/Nerdbank.MessagePack.Analyzers.Tests/ConverterAnalyzersTests.cs, test/Nerdbank.MessagePack.Tests/Nerdbank.MessagePack.Tests.csproj
A custom converter should always write or read exactly one msgpack structure. When multiple values need to be read or written, an array or map header must be used first to introduce the number of elements that belong to one super-structure.
Conditional branching, loops and `TryRead` methods can complicate static analysis in counting how many structures are actually read/written. I'm using roslyn's control flow analysis to help out. This API doesn't have any real samples from what I can tell, so I figured this out myself and I probably didn't get it quite right yet. I have several tests that show that at least certain cases work.
There are complex cases that the analyzer doesn't handle, which the design is to just bail out without reporting a diagnostic. So this analyzer does not guarantee …
=> Add `NBMsgPack031` analyzer for =1 structure being read/written in a custom converter

docfx/analyzers/NBMsgPack020.md, docfx/analyzers/NBMsgPack021.md, docfx/analyzers/NBMsgPack030.md, docfx/analyzers/NBMsgPack031.md, docfx/docs/custom-converters.md, src/Nerdbank.MessagePack/Converters/ArrayConverter`1.cs, src/Nerdbank.MessagePack/Converters/ArrayWithFlattenedDimensionsConverter`2.cs, src/Nerdbank.MessagePack/Converters/ArrayWithNestedDimensionsConverter`2.cs, src/Nerdbank.MessagePack/Converters/CommonRecords.cs, src/Nerdbank.MessagePack/Converters/DelayedConverter`1.cs, src/Nerdbank.MessagePack/Converters/DictionaryConverter`3.cs, src/Nerdbank.MessagePack/Converters/EnumAsOrdinalConverter`2.cs, src/Nerdbank.MessagePack/Converters/EnumerableConverter`2.cs, src/Nerdbank.MessagePack/Converters/IntConverters.cs, src/Nerdbank.MessagePack/Converters/IntConverters.tt, src/Nerdbank.MessagePack/Converters/ObjectArrayConverter`1.cs, src/Nerdbank.MessagePack/Converters/ObjectMapConverter`1.cs, src/Nerdbank.MessagePack/Converters/PrimitiveConverters.cs, src/Nerdbank.MessagePack/Converters/SubTypeUnionConverter`1.cs, src/Nerdbank.MessagePack/MessagePackConverter`1.cs, src/Nerdbank.MessagePack/MessagePackSerializer.cs, src/Nerdbank.MessagePack/PublicAPI.Unshipped.txt, src/Nerdbank.MessagePack/StandardVisitor.cs, test/Nerdbank.MessagePack.Analyzers.Tests/ConverterAnalyzersTests.cs, test/Nerdbank.MessagePack.Analyzers.Tests/MessagePackConverterAttributeAnalyzerTests.cs, test/Nerdbank.MessagePack.Tests/CustomConverterTests.cs, test/Nerdbank.MessagePack.Tests/MessagePackConverterAttributeTests.cs
This dramatically improves usability (and potentially perf as well), particularly for folks writing custom converters.
=> Accept values to be serialized with `in` instead of `ref`

Directory.Packages.props, docfx/docs/security.md, src/Nerdbank.MessagePack/ByValueEqualityComparer`1.cs, src/Nerdbank.MessagePack/ByValueEqualityComparer`2.cs, src/Nerdbank.MessagePack/IDeepSecureEqualityComparer`1.cs, src/Nerdbank.MessagePack/PublicAPI.Unshipped.txt, src/Nerdbank.MessagePack/SecureHash/ByValueAggregatingEqualityComparer`1.cs, src/Nerdbank.MessagePack/SecureHash/ByValueByteArrayEqualityComparer.cs, src/Nerdbank.MessagePack/SecureHash/ByValueCustomEqualityComparer`1.cs, src/Nerdbank.MessagePack/SecureHash/ByValueDictionaryEqualityComparer`3.cs, src/Nerdbank.MessagePack/SecureHash/ByValueEnumerableEqualityComparer`2.cs, src/Nerdbank.MessagePack/SecureHash/ByValueNullableEqualityComparer`1.cs, src/Nerdbank.MessagePack/SecureHash/ByValuePropertyEqualityComparer`2.cs, src/Nerdbank.MessagePack/SecureHash/ByValueVisitor.cs, src/Nerdbank.MessagePack/SecureHash/CollisionResistantHasherUnmanaged`1.cs, src/Nerdbank.MessagePack/SecureHash/HashResistantPrimitives.cs, src/Nerdbank.MessagePack/SecureHash/SecureAggregatingEqualityComparer`1.cs, src/Nerdbank.MessagePack/SecureHash/SecureCustomEqualityComparer`1.cs, src/Nerdbank.MessagePack/SecureHash/SecureDictionaryEqualityComparer`3.cs, src/Nerdbank.MessagePack/SecureHash/SecureEnumerableEqualityComparer`2.cs, src/Nerdbank.MessagePack/SecureHash/SecureEqualityComparer`1.cs, src/Nerdbank.MessagePack/SecureHash/SecureNullableEqualityComparer`1.cs, src/Nerdbank.MessagePack/SecureHash/SecurePropertyEqualityComparer`2.cs, src/Nerdbank.MessagePack/SecureHash/SecureVisitor.cs, src/Nerdbank.MessagePack/SecureHash/SipHash.cs, test/Nerdbank.MessagePack.Tests/ByValueEqualityComparerTests.cs, test/Nerdbank.MessagePack.Tests/Nerdbank.MessagePack.Tests.csproj
This makes it easy to use secure, hash-collision resistant equality comparer with arbitrary types for safely deserializing data.
This improves the #33 story, but doesn't close it.
=> Offer automatic secure hash functions

src/Nerdbank.MessagePack/BufferWriter.cs, src/Nerdbank.MessagePack/Converters/ArrayConverter`1.cs, src/Nerdbank.MessagePack/Converters/CommonRecords.cs, src/Nerdbank.MessagePack/Converters/DictionaryConverter`3.cs, src/Nerdbank.MessagePack/Converters/EnumerableConverter`2.cs, src/Nerdbank.MessagePack/Converters/ObjectArrayConverter`1.cs, src/Nerdbank.MessagePack/Converters/ObjectArrayWithNonDefaultCtorConverter`2.cs, src/Nerdbank.MessagePack/Converters/ObjectMapConverter`1.cs, src/Nerdbank.MessagePack/Converters/ObjectMapWithNonDefaultCtorConverter`2.cs, src/Nerdbank.MessagePack/Converters/RawMessagePackConverter.cs, src/Nerdbank.MessagePack/MessagePackAsyncReader.cs, src/Nerdbank.MessagePack/MessagePackAsyncWriter.cs, src/Nerdbank.MessagePack/MessagePackWriter.cs, src/Nerdbank.MessagePack/PublicAPI.Unshipped.txt, src/Nerdbank.MessagePack/RawMessagePack.cs, src/Nerdbank.MessagePack/StandardVisitor.cs, test/Nerdbank.MessagePack.Tests/RawMessagePackTests.cs
- async _serialize_ dropped from a 25-66% async tax to roughly 0.
- async _deserialize_ dropped from a 1100% async task to 400-800%. 
DeserializeAsync obviously needs more work, but there are plenty opportunities for improvement.
In the following metrics, pay attention to the improved ratios instead of looking at the Mean column, which shows significant regressions for unchanged code paths and it didn't repro later.
| Method                      | Categories             | Mean        | Error     | StdDev    | Ratio | RatioSD |
|---------------------------- |----------------------- |------------:|----------:|----------:|------:|--------:|
| DeserializeAsArrayInit      | array-init,Deserialize |    54.43 ns |  0.289 ns |  0.256 ns |  1.00 |    0.01 |
| DeserializeAsyncAsArrayInit | …
=> Leverage C# 13 to simplify and optimize async serialization

src/Nerdbank.MessagePack/Converters/ObjectArrayConverter`1.cs, src/Nerdbank.MessagePack/MessagePackSerializer.AutomatedFriendlyOverloads.tt, test/Nerdbank.MessagePack.Tests/MessagePackSerializerTestBase.cs, test/Nerdbank.MessagePack.Tests/ObjectsAsArraysTests.cs
Fix a mixed use of sync and async writers that led to data corruption in the serialized output.
Also:
- Add logging of async msgpack in tests.
- Fix T4 compilation warnings.
=> Fix async serialization corruption

docfx/docs/customizing-serialization.md, docfx/docs/migrating.md, samples/CustomizingSerialization.cs, src/Nerdbank.MessagePack/Converters/ObjectArrayConverter`1.cs, src/Nerdbank.MessagePack/Converters/ObjectArrayWithNonDefaultCtorConverter`2.cs, src/Nerdbank.MessagePack/KeyAttribute.cs, src/Nerdbank.MessagePack/MessagePackAsyncReader.cs, src/Nerdbank.MessagePack/PublicAPI.Unshipped.txt, src/Nerdbank.MessagePack/StandardVisitor.cs, test/Nerdbank.MessagePack.Tests/MessagePackSerializerTestBase.cs, test/Nerdbank.MessagePack.Tests/ObjectsAsArraysTests.cs
Arrays are most compact when they are packed with data. But if there are 'holes' in the indexes (whether by missing indexes in the key attributes or by properties having default values and thus not serialized), a map that uses those same ordinal indexes as keys can be more compact.
With this new feature, the more compact of the two formats is automatically chosen (when `SerializeDefaultValues == false`) during serialization.
=> Support serializing index-based types as maps as well as arrays

src/Nerdbank.MessagePack/Converters/EnumerableConverter`2.cs, src/Nerdbank.MessagePack/Converters/PrimitiveConverters.cs, src/Nerdbank.MessagePack/MessagePackSerializer.cs, src/Nerdbank.MessagePack/MessagePackWriter.cs, test/Nerdbank.MessagePack.Tests/MessagePackSerializerTestBase.cs, test/Nerdbank.MessagePack.Tests/MessagePackSerializerTests.cs
Various forms of byte buffers (`byte[]`, `Memory<byte>` and `ReadOnlyMemory<byte>`) should serialize using msgpack's special binary buffer format as it is far more compact and faster than using a msgpack array of bytes. This change ensures we use the more efficient form when serializing.
This change also fixes deserialization so that it supports either form.
=> Improve byte buffer (de)serialization

LICENSE, THIRD-PARTY-NOTICES.TXT, src/Nerdbank.MessagePack/Converters/ArraysOfPrimitivesConverters.Generated.cs, src/Nerdbank.MessagePack/Converters/ArraysOfPrimitivesConverters.Generated.tt, src/Nerdbank.MessagePack/Converters/ArraysOfPrimitivesConverters.cs, src/Nerdbank.MessagePack/Nerdbank.MessagePack.csproj, src/Nerdbank.MessagePack/StandardVisitor.cs, test/Benchmarks/ArraysOfPrimitives.cs, test/Benchmarks/Benchmarks.csproj, test/Nerdbank.MessagePack.Tests/ArraysOfPrimitivesTests.cs
Optimize serialization of arrays of primitives
These are super-small values of predictable max size. The largest perf cost to these previously had been the very many `MessagePackWriter.Advance(int)` calls. But we can reduce that from one per array element to just one per array, which makes such arrays dramatically faster.
| Method           | Mean     | Error     | StdDev   | Gen0   | Allocated |
|----------------- |---------:|----------:|---------:|-------:|----------:|
| Bool_Deserialize | 37.32 μs |  8.097 μs | 0.444 μs | 1.1597 |   10024 B |
| Bool_Serialize   | 38.50 μs |  7.784 μs | 0.427 μs |      - |         - |
| Double_Serialize | 41.46 μs |  7.525 μs | 0.412 μs |      - |         - |
| Single_Serialize | 43.66 μs | 50.927 μs | 2.791 μs |      - |         - |
| Int16_Serialize …
=> Faster primitive arrays

.config/dotnet-tools.json, .devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/dependabot.yml, .github/workflows/libtemplate-update.yml, Directory.Packages.props, azure-pipelines/Get-CodeCovTool.ps1, azure-pipelines/Merge-CodeCoverage.ps1, azure-pipelines/artifacts/Variables.ps1, azure-pipelines/artifacts/_pipelines.ps1, azure-pipelines/artifacts/_stage_all.ps1, azure-pipelines/artifacts/coverageResults.ps1, azure-pipelines/build.yml, azure-pipelines/dotnet-test-cloud.ps1, azure-pipelines/publish-CodeCov.ps1, azure-pipelines/variables/DotNetSdkVersion.ps1, azure-pipelines/variables/_pipelines.ps1, src/Nerdbank.MessagePack.Analyzers.CodeFixes/Nerdbank.MessagePack.Analyzers.CodeFixes.csproj, src/Nerdbank.MessagePack.Analyzers/Nerdbank.MessagePack.Analyzers.csproj, tools/Install-DotNetSdk.ps1, tools/Install-NuGetCredProvider.ps1, tools/Set-EnvVars.ps1
- Bump docfx from 2.77.0 to 2.78.0 (#311)
- Fix libtemplate update workflow
- Avoid `dotnet format` hang
- Update devcontainer for latest SDK and extension
- Get dependabot to help us keep the .NET SDK current
- Bump docfx from 2.78.0 to 2.78.1 (#313)
- Bump Microsoft.NET.Test.Sdk from 17.11.1 to 17.12.0 (#312)
- Use `-LiteralPath` instead of `-Path` in ps1 scripts
- Replace `Nullable` with `PolySharp` as a dependency
=> Merge latest Library.Template

src/Nerdbank.MessagePack.Analyzers.CodeFixes/MigrationCodeFix.cs, src/Nerdbank.MessagePack.Analyzers/KeyAttributeUseAnalyzer.cs, src/Nerdbank.MessagePack.Analyzers/ReferenceSymbols.cs, src/Nerdbank.MessagePack.Analyzers/Strings.resx, src/Nerdbank.MessagePack/Converters/CommonRecords.cs, src/Nerdbank.MessagePack/StandardVisitor.cs, test/Nerdbank.MessagePack.Analyzers.Tests/KeyAttributeUseAnalyzerTests.cs, test/Nerdbank.MessagePack.Analyzers.Tests/MigrationAnalyzerTests.cs, test/Nerdbank.MessagePack.Tests/ObjectsAsArraysTests.cs, test/Nerdbank.MessagePack.Tests/ObjectsAsMapTests.cs
Also fix several issues found during migration.
- [Improve NBMsgPack001 when there is no syntax for the member](https://github.com/AArnott/Nerdbank.MessagePack/commit/cb91ec144193a8613cdb8b550ec57c4c99d9d29c)
- [Fix ignoring of getter-only properties in [Key] mode](https://github.com/AArnott/Nerdbank.MessagePack/commit/cd07d409061f84f1bccdcc4ecf532f30625af0f7)
- [Fix trivia preservation around changed/removed attributes](https://github.com/AArnott/Nerdbank.MessagePack/commit/320087a890797ab8caae902cd036923bf1e13f90)
- [Fix migration of nested converters](https://github.com/AArnott/Nerdbank.MessagePack/commit/5f7f6254c69de3fd0078f64f8b38bdf5a33b69dc)
=> Fix handling of getter-only properties on `[Key]` types

src/Nerdbank.MessagePack/Converters/EnumAsOrdinalConverter`2.cs, src/Nerdbank.MessagePack/Converters/EnumAsStringConverter`2.cs, src/Nerdbank.MessagePack/MessagePackSerializer.cs, src/Nerdbank.MessagePack/PublicAPI.Unshipped.txt, src/Nerdbank.MessagePack/StandardVisitor.cs, src/Nerdbank.MessagePack/StringEncoding.cs, test/Nerdbank.MessagePack.Tests/EnumTests.cs
Prior to this, enums would only serialize as their underlying integer type.
Closes #132
=> Add option to serialize enums by name

src/Nerdbank.MessagePack/Converters/HardwareAccelerated.cs
`float[]` / `double[]` serialization is relatively easy because the ratio of output byte count by input byte count is always constant.
The `const byte B = byte.MaxValue;` and `const byte F` is introduced for the sake of the readability of very long constant binaries.
Prev: #114
=> SIMD acceleration for float/double[]

Directory.Packages.props, src/Nerdbank.MessagePack/Converters/PrimitiveConverters.cs, src/Nerdbank.MessagePack/MessagePackSerializer.cs, src/Nerdbank.MessagePack/Nerdbank.MessagePack.csproj, src/Nerdbank.MessagePack/PublicAPI.Unshipped.txt, src/Nerdbank.MessagePack/ReferenceEqualityTracker.cs, src/Nerdbank.MessagePack/StandardVisitor.cs, test/Benchmarks/StringInterning.cs, test/Nerdbank.MessagePack.Tests/ReferencePreservationTests.cs, test/Nerdbank.MessagePack.Tests/StringInterningTests.cs
=> Add support for string interning

test/Benchmarks/ArraysOfMultipleCategoryPrimitives.cs, test/Benchmarks/ArraysOfPrimitives.cs
Current benchmark code for `long[]` only examines the values which would be encoded into 9 bytes in most cases.
This might lead to over-optimization on .NET runtime level and CPU arch level.
=> Add benchmarks for not bool/float/double primitive arrays.

samples/CustomConverters.cs, src/Nerdbank.MessagePack/Converters/ObjectMapConverter`1.cs, src/Nerdbank.MessagePack/Converters/ObjectMapWithNonDefaultCtorConverter`2.cs, src/Nerdbank.MessagePack/MessagePackAsyncReader.cs, src/Nerdbank.MessagePack/MessagePackReader.cs, src/Nerdbank.MessagePack/MessagePackStreamingReader.cs, src/Nerdbank.MessagePack/SerializationContext.cs, src/Nerdbank.MessagePack/net8.0/PublicAPI.Unshipped.txt, src/Nerdbank.MessagePack/netstandard2.0/PublicAPI.Unshipped.txt, test/Nerdbank.MessagePack.Tests/MessagePackStreamingReaderTests.cs
This is a perf optimization for streaming scenarios where a converter needs to skip a structure but the buffer may not have the entire structure in memory. This optimization records how much of the structure has been skipped already so that the reader can advance, freeing memory, and resume skipping when we get more bytes to decode.
In particular, this avoids the previous behavior that skipping had to be restarted from the beginning of the structure each time new bytes are brought in until the whole structure was in memory together.
While this is theoretically a memory use improvement (for skipping scenarios only), this is mostly about avoiding CPU work to parse partial structures repeatedly until we get the whole thing in memory. With this change, at most one msgpack *token* (rather than …
=> Implement stateful, incremental skip

src/Nerdbank.MessagePack/MessagePackSerializer.cs, src/Nerdbank.MessagePack/net8.0/PublicAPI.Unshipped.txt, src/Nerdbank.MessagePack/netstandard2.0/PublicAPI.Unshipped.txt, test/Nerdbank.MessagePack.Tests/AsyncSerializationTests.cs, test/Nerdbank.MessagePack.Tests/FragmentedPipeReader.cs, test/Nerdbank.MessagePack.Tests/MessagePackAsyncReaderTests.cs, test/Nerdbank.MessagePack.Tests/MessagePackSerializerTestBase.cs, test/Nerdbank.MessagePack.Tests/ObjectsAsArraysTests.cs
Since synchronous deserialization is substantially faster than async deserialization, we prefer sync. But sync requires that all msgpack data be pre-buffered. That's a reasonable trade-off, assuming the msgpack data is reasonably small. When it is large, the slower async path may be preferable to avoid unbounded memory consumption.
Closes #155
| Method            | Mean     | Error    | StdDev  | Ratio | RatioSD | Gen0    | Gen1   | Allocated | Alloc Ratio |
|------------------ |---------:|---------:|--------:|------:|--------:|--------:|-------:|----------:|------------:|
| Sync_Deserialize  | 111.4 us | 19.72 us | 1.08 us |  1.00 |    0.01 | 11.4746 | 1.9531 |  70.34 KB |        1.00 |
| Async_Deserialize | 327.0 us |  6.20 us | 0.34 us |  2.94 |    0.02 | 11.2305 | 1.9531 |  70.49 KB | …
=> Add `MessagePackSerializer.MaxAsyncBuffer` to speed up small async deserializations

docfx/analyzers/NBMsgPack050.md, docfx/analyzers/index.md, docfx/analyzers/toc.yml, samples/AnalyzerDocs/NBMsgPack050.cs, src/Nerdbank.MessagePack.Analyzers/AnalyzerReleases.Unshipped.md, src/Nerdbank.MessagePack.Analyzers/RefParametersForRefStructsAnalyzer.cs, src/Nerdbank.MessagePack.Analyzers/ReferenceSymbols.cs, src/Nerdbank.MessagePack.Analyzers/Strings.resx, src/Nerdbank.MessagePack/Converters/ArrayWithNestedDimensionsConverter`2.cs, test/Nerdbank.MessagePack.Analyzers.Tests/RefParametersForRefStructsAnalyzerTests.cs
=> Add analyzer to flag missing `ref` modifier on ref struct typed parameters

docfx/docs/migrating.md, docfx/docs/unions.md, samples/Unions.cs, src/Nerdbank.MessagePack.Analyzers/AnalyzerUtilities.cs, src/Nerdbank.MessagePack.Analyzers/KnownSubTypeAnalyzers.cs, src/Nerdbank.MessagePack/Converters/CommonRecords.cs, src/Nerdbank.MessagePack/Converters/ObjectMapConverter`1.cs, src/Nerdbank.MessagePack/Converters/ObjectMapWithNonDefaultCtorConverter`2.cs, src/Nerdbank.MessagePack/Converters/SubTypeUnionConverter`1.cs, src/Nerdbank.MessagePack/IKnownSubTypeMapping.cs, src/Nerdbank.MessagePack/KnownSubTypeAttribute.cs, src/Nerdbank.MessagePack/KnownSubTypeMapping`1.cs, src/Nerdbank.MessagePack/MessagePackSerializer.cs, src/Nerdbank.MessagePack/StandardVisitor.cs, src/Nerdbank.MessagePack/StringEncoding.cs, src/Nerdbank.MessagePack/SubTypeAlias.cs, src/Nerdbank.MessagePack/net8.0/PublicAPI.Unshipped.txt, src/Nerdbank.MessagePack/netstandard2.0/PublicAPI.Unshipped.txt, test/Nerdbank.MessagePack.Analyzers.Tests/KnownSubTypeAnalyzersTests.cs, test/Nerdbank.MessagePack.Tests/KnownSubTypeMappingTests.cs, test/Nerdbank.MessagePack.Tests/KnownSubTypeTests.cs, test/Nerdbank.MessagePack.Tests/ReferencePreservationTests.cs, test/Nerdbank.MessagePack.Tests/SchemaTests.cs
- Add support for dynamic registration of sub-types.
- Add support for `string` aliases for known sub-types.
- Add support for inferring a string alias for subtypes using `Type.FullName`.
Closes #36
=> Improve known sub-type support

Directory.Packages.props, test/Nerdbank.MessagePack.Tests/Nerdbank.MessagePack.Tests.csproj
That way, we don't bring in .NET 9 packages for .NET 8 apps that include libraries that compiled against .NET Standard 2.0 and referenced _this_ package.
=> Reference .NET 8 era packages for .NET Standard

azure-pipelines/dotnet-test-cloud.ps1, src/Nerdbank.MessagePack/RawMessagePack.cs, src/Nerdbank.MessagePack/net8.0/PublicAPI.Unshipped.txt, src/Nerdbank.MessagePack/netstandard2.0/PublicAPI.Unshipped.txt, test/Nerdbank.MessagePack.Tests/RawMessagePackTests.cs
"Downcasts" should be explicit while upcasts remain implicit.
=> To-`RawMessagePack` conversion operators should be explicit

src/Nerdbank.MessagePack/Converters/PrimitiveConverterLookup.cs, src/Nerdbank.MessagePack/Converters/PrimitiveConverterLookup.tt, src/Nerdbank.MessagePack/Converters/PrimitiveConverters.cs, src/Nerdbank.MessagePack/MessagePackSerializer.cs, src/Nerdbank.MessagePack/Nerdbank.MessagePack.csproj, src/Nerdbank.MessagePack/StandardVisitor.cs
Instead of instantiating all built-in converters on startup unconditionally or referencing all the supported data types themselves, use a generic method so that the JIT will remove references to data types (and their converters) that are never serialized in the application.
It may not be intuitive, but indeed a long C# method of type checks _does_ offer this trim optimization, because the JIT / AOT compiler will remove type checks that will never match given the type argument on the generic method, thereby removing the unrelated type references, leaving only those behind that are actually going to be used.
Accrues toward #190, by bringing the AOT console test app down from 3.9MB to just under 3.6MB.
=> Allow more effective trimming

samples/CustomConverters.cs, src/Nerdbank.MessagePack/MessagePackWriter.cs, src/Nerdbank.MessagePack/net8.0/PublicAPI.Unshipped.txt, src/Nerdbank.MessagePack/netstandard2.0/PublicAPI.Unshipped.txt, test/Nerdbank.MessagePack.Tests/MessagePackWriterTests.cs
Hopefully reduce the need for the analyzer requested in #198.
=> Add friendlier `MessagePackWriter.Write(MessagePackString)` method

Directory.Packages.props
It is no longer required now that we compile with the latest SDK
=> Remove explicit System.Formats.Asn1 version

src/Nerdbank.MessagePack/BufferWriter.cs, src/Nerdbank.MessagePack/Converters/PrimitiveConverters.cs, src/Nerdbank.MessagePack/MessagePackSerializer.FriendlyOverloads.cs, src/Nerdbank.MessagePack/MessagePackStreamingReader.cs, src/Nerdbank.MessagePack/MessagePackWriter.cs, src/Nerdbank.MessagePack/SequencePool`1.cs, src/Nerdbank.MessagePack/net8.0/PublicAPI.Unshipped.txt, src/Nerdbank.MessagePack/netstandard2.0/PublicAPI.Unshipped.txt, test/Nerdbank.MessagePack.Tests/AsyncSerializationTests.cs, test/Nerdbank.MessagePack.Tests/FragmentedPipeReader.cs
This doesn't change how we work when _interning_ strings.
It also doesn't incrementally _encode_ strings during async serialization. But we could add that if needed.
=> Decode strings incrementally during async deserialization

Directory.Packages.props, docfx/docs/byvalue-equality.md, docfx/docs/custom-converters.md, docfx/docs/migrating.md, docfx/docs/surrogate-types.md, docfx/docs/toc.yml, samples/SurrogateTypes.cs, src/Nerdbank.MessagePack/ByValueEqualityComparer.cs, src/Nerdbank.MessagePack/Converters/SurrogateConverter`2.cs, src/Nerdbank.MessagePack/ReferencePreservingVisitor.cs, src/Nerdbank.MessagePack/SecureHash/ByValueVisitor.cs, src/Nerdbank.MessagePack/SecureHash/SecureVisitor.cs, src/Nerdbank.MessagePack/SecureHash/SurrogateEqualityComparer`2.cs, src/Nerdbank.MessagePack/SecureHash/SurrogateSecureEqualityComparer`2.cs, src/Nerdbank.MessagePack/StandardVisitor.cs, test/Nerdbank.MessagePack.Tests/ReferencePreservationTests.cs, test/Nerdbank.MessagePack.Tests/Resources/KnownGoodSchemas/Surrogates.schema.json, test/Nerdbank.MessagePack.Tests/SchemaTests.cs, test/Nerdbank.MessagePack.Tests/SurrogateTests.cs
Surrogates provide a much easier alternative to implementing a custom converter for types that are not serializable.
=> Implement support for surrogates

src/Nerdbank.MessagePack/MessagePackSerializer.cs
This actually ensures that certain values (e.g. `double.MaxValue`) can be deserialized later, since otherwise it will round *up*, going *beyond* `double.MaxValue`.
Thanks to @guojiancong for finding and sharing this (with MessagePack-CSharp).
=> Format `float` and `double` values as JSON with full precision

src/Nerdbank.MessagePack/Converters/ObjectArrayConverter`1.cs, src/Nerdbank.MessagePack/Converters/ObjectConverterBase`1.cs, test/Nerdbank.MessagePack.Tests/Resources/KnownGoodSchemas/BasicObject_Key.schema.json, test/Nerdbank.MessagePack.Tests/Resources/KnownGoodSchemas/BasicObject_Key_Required.schema.json, test/Nerdbank.MessagePack.Tests/SchemaTests.cs
- Fix `required` property to use index-based property names to match the object schema.
- Add `minItems` property to reflect the required number of array elements.
- Include property name in the `description` property for indexed elements.
=> Improve exported JSON schemas for array of values objects

docfx/docs/customizing-serialization.md, src/Nerdbank.MessagePack/ConverterCache.cs, src/Nerdbank.MessagePack/Converters/ObjectArrayConverter`1.cs, src/Nerdbank.MessagePack/Converters/ObjectArrayWithNonDefaultCtorConverter`2.cs, src/Nerdbank.MessagePack/Converters/ObjectMapConverter`1.cs, src/Nerdbank.MessagePack/Converters/ObjectMapWithNonDefaultCtorConverter`2.cs, src/Nerdbank.MessagePack/KeyAttribute.cs, src/Nerdbank.MessagePack/MessagePackSerializer.cs, src/Nerdbank.MessagePack/SerializeDefaultValuesPolicy.cs, src/Nerdbank.MessagePack/StandardVisitor.cs, src/Nerdbank.MessagePack/net8.0/PublicAPI.Unshipped.txt, src/Nerdbank.MessagePack/netstandard2.0/PublicAPI.Unshipped.txt, test/Benchmarks/ArraysOfMultipleCategoryPrimitives.cs, test/Benchmarks/ArraysOfPrimitives.cs, test/Benchmarks/SimplePoco.cs, test/Nerdbank.MessagePack.Tests/ObjectsAsArraysTests.cs, test/Nerdbank.MessagePack.Tests/ShouldSerializeTests.cs
Before, the choice was boolean: do you want to serialize properties with default values or not?
Now, it's a flags enum that allows you to choose always and never (as before), but also properties that are `required` (per C# rules), value types and/or ref types.
=> Provide more flexibility in which properties to serialize default values of

src/Nerdbank.MessagePack/MessagePackAsyncReader.cs, src/Nerdbank.MessagePack/MessagePackSerializer.cs, src/Nerdbank.MessagePack/net8.0/PublicAPI.Unshipped.txt, src/Nerdbank.MessagePack/netstandard2.0/PublicAPI.Unshipped.txt, test/Nerdbank.MessagePack.Tests/AsyncSerializationTests.cs, test/Nerdbank.MessagePack.Tests/MessagePackAsyncReaderTests.cs
Prior to this fix, the `MessagePackSerializer.DeserializeAsync<T>(PipeReader, ...)` methods would leave the `PipeReader` in an undefined state.
=> Fix PipeReader position after an async deserialization

src/Nerdbank.MessagePack/Extension.cs, src/Nerdbank.MessagePack/RawMessagePack.cs, src/Nerdbank.MessagePack/Utilities/ReadOnlySequenceExtensions.cs, src/Nerdbank.MessagePack/net8.0/PublicAPI.Unshipped.txt, src/Nerdbank.MessagePack/netstandard2.0/PublicAPI.Unshipped.txt, test/Nerdbank.MessagePack.Tests/ExtensionTests.cs
This pull request includes several changes to the `Nerdbank.MessagePack` library, focusing on improving the equality checks and updating the `Extension` struct. The most significant changes include the addition of equality and hash code methods, the removal of a redundant method, and the introduction of new tests for equality and hash code verification.
* [`src/Nerdbank.MessagePack/Extension.cs`](diffhunk://#diff-14c13e2f1a37fe61f6ea08be93b041654d4515620cca6f949dd74967a9ba3e2bL18-R32): Added `Equals` and `GetHashCode` methods to the `Extension` struct to improve equality checks and hash code generation.
* [`src/Nerdbank.MessagePack/RawMessagePack.cs`](diffhunk://#diff-9e5da3f37b04cce622d8e25b814573807e593a3373b0fe6a6b7ec873cd9fb781L113-L178): Removed the private `SequenceEqual` method and …
=> `Extension` struct enhancements

src/Nerdbank.MessagePack/MessagePackStreamingReader.cs, test/Nerdbank.MessagePack.Tests/MessagePackStreamingReaderTests.cs
Fix MessagePackStreamingReader multi-read methods in insufficient buffer scenarios
Several read methods read a header and then the data in two steps as an implementation detail. When there is sufficient buffer to read the first time, but insufficient the second time, these methods were all failing to "rewind" the reader so that buffering more and retrying could be done from the original point. These bugs led to a `TokenMismatch` error on subsequent attempts.
Fixed APIs are:
- `MessagePackStreamingReader.TryRead(out Extension)`
- `MessagePackStreamingReader.TryReadBinary`
- `MessagePackStreamingReader.TryRead(out string)`
- `MessagePackStreamingReader.TryReadStringSequence`
- `MessagePackStreamingReader.TryReadStringSpan`
=> Fix header+body based `TryRead` methods on `MessagePackStreamingReader`

docfx/docs/streaming-deserialization.md, samples/StreamingDeserialization.cs, src/Nerdbank.MessagePack/Converters/DictionaryConverter`3.cs, src/Nerdbank.MessagePack/Converters/EnumerableConverter`2.cs, src/Nerdbank.MessagePack/Converters/ObjectArrayConverter`1.cs, src/Nerdbank.MessagePack/Converters/ObjectMapConverter`1.cs, src/Nerdbank.MessagePack/Converters/ObjectMapWithNonDefaultCtorConverter`2.cs, src/Nerdbank.MessagePack/IMessagePackConverter.cs, src/Nerdbank.MessagePack/MessagePackAsyncReader.cs, src/Nerdbank.MessagePack/MessagePackConverter`1.cs, src/Nerdbank.MessagePack/MessagePackReader.cs, src/Nerdbank.MessagePack/MessagePackSerializer.AutomatedFriendlyOverloads.cs, src/Nerdbank.MessagePack/MessagePackSerializer.AutomatedFriendlyOverloads.tt, src/Nerdbank.MessagePack/MessagePackSerializer.FriendlyOverloads.cs, src/Nerdbank.MessagePack/MessagePackSerializer.cs, src/Nerdbank.MessagePack/MessagePackStreamingReader.Integers.cs, src/Nerdbank.MessagePack/MessagePackStreamingReader.Integers.tt, src/Nerdbank.MessagePack/MessagePackStreamingReader.cs, src/Nerdbank.MessagePack/SerializationContext.cs, src/Nerdbank.MessagePack/StreamingDeserializer`1.cs, src/Nerdbank.MessagePack/net8.0/PublicAPI.Unshipped.txt, src/Nerdbank.MessagePack/netstandard2.0/PublicAPI.Unshipped.txt, test/Nerdbank.MessagePack.Tests/AsyncSerializationTests.cs, test/Nerdbank.MessagePack.Tests/StreamingEnumerableTests.cs
This pull request includes several changes to enhance the streaming deserialization capabilities and add new asynchronous methods for skipping to specific values within MessagePack data. The most important changes include updates to the documentation, the addition of new methods for asynchronous skipping, and modifications to existing converters to support these new methods.
* [`docfx/docs/streaming-deserialization.md`](diffhunk://#diff-4ab4ab7b6858efcbeeb604190c7fbbc55afa94b11390f5183ab1f7448382305eL21-R21): Updated to reflect the use of `StreamingEnumerationOptions` instead of JSONPath for navigating through envelopes in MessagePack structures. [[1]](diffhunk://#diff-4ab4ab7b6858efcbeeb604190c7fbbc55afa94b11390f5183ab1f7448382305eL21-R21) …
=> Add streaming enumeration of sequences with envelopes 

src/Nerdbank.MessagePack/Converters/ObjectMapConverter`1.cs, src/Nerdbank.MessagePack/Converters/ObjectMapWithNonDefaultCtorConverter`2.cs, src/Nerdbank.MessagePack/MessagePackAsyncReader.cs, src/Nerdbank.MessagePack/MessagePackStreamingReader.cs, test/Nerdbank.MessagePack.Tests/MessagePackStreamingReaderTests.cs, test/Nerdbank.MessagePack.Tests/ObjectsAsMapTests.cs, test/Nerdbank.MessagePack.Tests/StreamingEnumerableTests.cs
- Fix async deserialization of maps with particular buffer boundaries
In particular, when the buffer boundary happens to be between a property name and its value and the value prefers to be deserialized synchronously, we had a bug where we'd read the property name, then expect to be able to read it again. 
- Fix exception when enumerating top-level elements from an empty buffer
Fixes both issues reported in #242
=> Fix bugs in async deserialization

src/Nerdbank.MessagePack/Converters/PrimitiveConverters.cs, src/Nerdbank.MessagePack/MessagePackAsyncReader.cs, src/Nerdbank.MessagePack/MessagePackSerializer.cs, src/Nerdbank.MessagePack/StreamingDeserializer`1.cs, test/Nerdbank.MessagePack.Tests/StreamingEnumerableTests.cs
- Improve string deserialization perf overall (from `DeserializeAsync` methods)
- Opportunistically use synchronous deserialization during async enumeration of top-level elements when we have the next item buffered already anyway.
- Use sync deserialization opportunistically during async enumeration with envelopes
Together, this gets the async top-level enumeration scenario from 38% slower than MessagePack-CSharp to 14% _faster_.
Closes #253
=> Improve async deserialization performance

src/Nerdbank.MessagePack/MessagePackAsyncReader.cs, src/Nerdbank.MessagePack/MessagePackSerializer.cs, test/Nerdbank.MessagePack.Tests/FragmentedPipeReader.cs, test/Nerdbank.MessagePack.Tests/StreamingEnumerableTests.cs
=> Fix hang waiting for more data when async enumerable elements are already in the buffer

test/Nerdbank.MessagePack.Tests/CustomEnumerableTypes.cs
@robertoschiabel started a discussion over at MessagePack-CSharp because that library fails at source generation for custom list collections. 
I was curious to see whether Nerdbank.MessagePack could handle it. To my delight, it Just Works. :)
=> Add test to verify a custom collection type can be serialized

.gitignore, src/Nerdbank.MessagePack/ConverterCache.cs, src/Nerdbank.MessagePack/StandardVisitor.cs, src/Nerdbank.MessagePack/Utilities/SpanDictionary.cs, test/Benchmarks/Benchmarks.csproj, test/Benchmarks/Data.cs, test/Benchmarks/STJSourceGenerationContext.cs, test/Benchmarks/SimplePoco.cs, test/Benchmarks/SyncVsAsyncPoco.cs, test/Benchmarks/Usings.cs
* We skip hashing strings when matching property names when the input has a length that does not match two or more known property names.
* Cache the last top-level converter to be used in a field to avoid dictionary lookups on repeated serialization jobs.
* Added JSON serialization and deserialization benchmarks using `System.Text.Json` and source generation context to include comparisons between MsgPack and JSON serialization.
* Upgraded target framework for benchmarks from `net8.0` to `net9.0` to leverage new features and improvements (`test/Benchmarks/Benchmarks.csproj`).
| Method                               | Categories             | Mean     | Error    | StdDev  | Ratio | RatioSD | Gen0   | Allocated | Alloc Ratio |
|------------------------------------- |----------------------- …
=> Dictionary lookup perf optimizations

Directory.Packages.props, src/Nerdbank.MessagePack/Converters/CommonRecords.cs, src/Nerdbank.MessagePack/ReferencePreservingVisitor.cs, src/Nerdbank.MessagePack/StandardVisitor.cs
Bump PolyType to 0.30.1
This update removes the `ITypeShapeVisitor` interface.
=> Bump PolyType to 0.30.1

.github/renovate.json, Directory.Packages.props, test/Nerdbank.MessagePack.Tests/Nerdbank.MessagePack.Tests.csproj
This allows an ASP.NET Core app to target .NET 8 without having to ship System.IO.Pipelines.dll with the app, since it's included in the runtime.
=> Reference System.IO.Pipelines 8.0 instead of 9.0

docfx/docs/custom-converters.md, samples/cs/CustomConverters.cs, samples/cs/Unions.cs, src/Nerdbank.MessagePack/ConverterCache.cs, src/Nerdbank.MessagePack/ConverterCollection.cs, src/Nerdbank.MessagePack/ConverterTypeCollection.cs, src/Nerdbank.MessagePack/DerivedTypeMapping.cs, src/Nerdbank.MessagePack/DerivedTypeMappingCollection.cs, src/Nerdbank.MessagePack/DerivedTypeMapping`1.cs, src/Nerdbank.MessagePack/MessagePackConverter.cs, src/Nerdbank.MessagePack/MessagePackConverter`1.cs, src/Nerdbank.MessagePack/MessagePackSerializer.GetSchema.cs, src/Nerdbank.MessagePack/MessagePackSerializer.cs, src/Nerdbank.MessagePack/SerializerConfiguration.cs, test/Nerdbank.MessagePack.Tests/AsyncSerializationTests.cs, test/Nerdbank.MessagePack.Tests/CustomConverterFactoryTests.cs, test/Nerdbank.MessagePack.Tests/CustomConverterTests.cs, test/Nerdbank.MessagePack.Tests/DerivedTypeTests.cs, test/Nerdbank.MessagePack.Tests/MessagePackSerializerTests.cs, test/Nerdbank.MessagePack.Tests/ReferencePreservationTests.cs, test/Nerdbank.MessagePack.Tests/SchemaTests.cs
This resolves the mix of thread-safe and non-thread-safe APIs that were previously on the class.
=> Refactor `MessagePackSerializer` to be entirely immutable

Directory.Packages.props, docfx/docs/built-in-converters.md, docfx/docs/getting-started.md, docfx/docs/migrating.md, docfx/docs/toc.yml, samples/cs/PrimitiveDeserialization.cs, samples/cs/Samples.csproj, src/Nerdbank.MessagePack/Converters/ExpandoObjectConverter.cs, src/Nerdbank.MessagePack/Converters/JsonDocumentConverter.cs, src/Nerdbank.MessagePack/Converters/JsonElementConverter.cs, src/Nerdbank.MessagePack/Converters/JsonNodeConverter.cs, src/Nerdbank.MessagePack/Converters/PrimitiveConverterLookup.cs, src/Nerdbank.MessagePack/Converters/PrimitiveConverterLookup.tt, src/Nerdbank.MessagePack/Converters/PrimitivesOnlyReader.cs, src/Nerdbank.MessagePack/DynamicDictionary.cs, src/Nerdbank.MessagePack/MessagePackReader.cs, src/Nerdbank.MessagePack/MessagePackSerializer.cs, src/Nerdbank.MessagePack/MsgPackPrimitivesWitness.cs, test/Nerdbank.MessagePack.Tests/Converters/ExpandoObjectConverterTests.cs, test/Nerdbank.MessagePack.Tests/Converters/JsonDocumentConverterTests.cs, test/Nerdbank.MessagePack.Tests/Converters/JsonElementConverterTests.cs, test/Nerdbank.MessagePack.Tests/Converters/JsonNodeConverterTests.cs, test/Nerdbank.MessagePack.Tests/DynamicSerializationTests.cs, test/Nerdbank.MessagePack.Tests/MessagePackSerializerTestBase.cs, test/Nerdbank.MessagePack.Tests/MessagePackSerializerTests.cs, test/Nerdbank.MessagePack.Tests/ReflectionShapeProviderTests.cs, test/Nerdbank.MessagePack.Tests/SharedTestCases.cs, test/Nerdbank.MessagePack.Tests/StreamingEnumerableTests.cs
Adds the following method to `MessagePackSerializer` for typeless deserialization:
```cs
public static dynamic? DeserializeDynamic(ref MessagePackReader reader)
```
This allows for javascript-like decoding:
```cs
dynamic deserialized = MessagePackSerializer.DeserializeDynamic(ref reader)!;
Assert.NotNull(deserialized);
Assert.Equal("Value1", deserialized.Prop1);
Assert.Equal(42, (int)deserialized.Prop2);
Assert.Equal(3, deserialized.deeper.Length);
Assert.Equal(true, deserialized.deeper[0]);
Assert.Equal(3.5, deserialized.deeper[1]);
Assert.Equal(new Extension(15, new byte[] { 1, 2, 3 }), deserialized.deeper[2]);
Assert.Equal(new byte[] { 1, 2, 3 }, deserialized[45UL]);
```
Closes #330
=> Add `DeserializeDynamic` method for typeless deserialization

samples/cs/CustomConverters.cs, src/Nerdbank.MessagePack/ConverterCache.cs, src/Nerdbank.MessagePack/IMessagePackConverterFactory.cs, test/Nerdbank.MessagePack.Tests/CustomConverterFactoryTests.cs
This is important so that PolyType associated types can be retrieved from the shape.
=> Offer the `ITypeShape<T>` to converter factories

src/Nerdbank.MessagePack/DerivedTypeMappingCollection.cs, test/Nerdbank.MessagePack.Tests/DerivedTypeMappingTests.cs, test/Nerdbank.MessagePack.Tests/Usings.cs
This bug led to NRE being thrown from DerivedTypeMappingCollection when users use collection literals syntax that adds mappings to a non-empty mappings collection.
Fixes #361
=> Fix enumeration of `DerivedTypeMappingCollection`

src/Nerdbank.MessagePack/StandardVisitor.cs, test/Nerdbank.MessagePack.Tests/MessagePackSerializerTests.cs
Instead of serializing a `Tuple<int, bool>` or `ValueTuple<int, bool>` as:
```json
{ "Item1": 42, "Item2": true }
```
They will serialize as simply:
```json
[42, true]
```
=> Serialize tuples as arrays instead of maps

.github/workflows/build.yml, Directory.Build.props, Directory.Build.rsp, Directory.Build.targets, Directory.Traversal.targets, Nerdbank.MessagePack.slnx, global.json, src/Nerdbank.MessagePack/Converters/ExpandoObjectConverter.cs, src/Nerdbank.MessagePack/Converters/PrimitiveConverterLookup.cs, src/Nerdbank.MessagePack/Converters/PrimitiveConverterLookup.tt, src/Nerdbank.MessagePack/Converters/PrimitivesAsDynamicConverter.cs, src/Nerdbank.MessagePack/Converters/PrimitivesAsObjectConverter.cs, src/Nerdbank.MessagePack/DynamicDictionary.cs, src/Nerdbank.MessagePack/MessagePackSerializer.cs, src/Nerdbank.MessagePack/Reasons.cs, src/dirs.proj, test/AOT.props, test/AotNativeConsole/AotNativeConsole.csproj, test/Nerdbank.MessagePack.Tests/Converters/ExpandoObjectConverterTests.cs, test/dirs.proj, tools/dirs.proj
This change takes the approach of moving functionality that (currently) requires dynamic runtime capability to separate APIs that must be invoked separately.
Ideally though, `DynamicDictionary` could be rewritten to be more like `ExpandoObject`, which has no such dependency.
Fixes #405
This works around https://github.com/dotnet/msbuild/issues/11922
=> Add Native AOT validation and split out dynamic behavior

docfx/docs/custom-converters.md, samples/cs/CustomConverters.cs, src/Nerdbank.MessagePack.Analyzers/MessagePackConverterAttributeAnalyzer.cs, src/Nerdbank.MessagePack/MessagePackConverterAttribute.cs, src/Nerdbank.MessagePack/StandardVisitor.cs, test/Nerdbank.MessagePack.Analyzers.Tests/MessagePackConverterAttributeAnalyzerTests.cs, test/Nerdbank.MessagePack.Tests/MessagePackConverterAttributeTests.cs
This includes a workaround for https://github.com/eiriktsarpalis/PolyType/issues/181
Closes #420
=> Add support for `[MessagePackConverter]` to be applied to properties and fields

Directory.Packages.props, test/Nerdbank.MessagePack.Tests/MessagePackConverterAttributeTests.cs
Bump PolyType and remove workaround
=> Create associated type automatically when `[MessagePackConverter]` is applied to members

Directory.Packages.props, docfx/docs/built-in-converters.md, docfx/docs/toc.yml, src/Nerdbank.MessagePack/Converters/ExpandoObjectConverter.cs, src/Nerdbank.MessagePack/Converters/PrimitivesAsDynamicConverter.cs, src/Nerdbank.MessagePack/Converters/PrimitivesAsObjectConverter.cs, src/Nerdbank.MessagePack/OptionalConverters.cs, test/Nerdbank.MessagePack.Tests/ArchitectureRules.cs, test/Nerdbank.MessagePack.Tests/Converters/ExpandoObjectConverterTests.cs, test/Nerdbank.MessagePack.Tests/Nerdbank.MessagePack.Tests.csproj
All optional converters are now accessible exclusively through the `OptionalConverters` class.
=> Remove the Converters sub-namespace

CONTRIBUTING.md, src/Nerdbank.MessagePack/Converters/CommonRecords.cs, src/Nerdbank.MessagePack/StandardVisitor.cs
This reduces NativeAOT code size from 7,171 KB to 6,969 KB by removing the unnecessary `IEquatable<T>` implementations over user-defined types.
=> Convert some records to classes

src/Nerdbank.MessagePack/Extension.cs, src/Nerdbank.MessagePack/MessagePackValue.cs, src/Nerdbank.MessagePack/SecureHash/HashCollisionResistantPrimitives.cs, test/Nerdbank.MessagePack.Tests/DynamicSerializationTests.cs, test/Nerdbank.MessagePack.Tests/ExtensionTests.cs, test/Nerdbank.MessagePack.Tests/MessagePackSerializerTestBase.cs, test/Nerdbank.MessagePack.Tests/MessagePackValueTests.cs
This also _moves_ structural equality for `MessagePackValue` to the interface implementation. The ordinary `Equals` and `GetHashCode` overrides are now 'shallow' to match typical .NET patterns.
It also implements `GetHashCode` on `MessagePackValue` which previously was _not_ implemented, leading to unexpected hash code vs. Equals results.
=> Implement `IDeepSecureEqualityComparer<T>` on `MessagePackValue` and `Extension`

src/Nerdbank.MessagePack/Converters/DictionaryConverter`3.cs, src/Nerdbank.MessagePack/Converters/EnumerableConverter`2.cs, src/Nerdbank.MessagePack/Converters/PolyTypeExtensions.cs
This avoids the needless resize/copy that happens as we deserialize a mutable collection.
=> Initialize mutable collections with appropriate capacity

src/Nerdbank.MessagePack/MessagePackConverterAttribute.cs, src/Nerdbank.MessagePack/StandardVisitor.cs, test/Nerdbank.MessagePack.Tests/MessagePackConverterAttributeTests.cs
Add support for `MessagePackConverterAttribute` to appear on enum types
=> Add support for `MessagePackConverterAttribute` to appear on enum types

.github/workflows/build.yml, src/Nerdbank.MessagePack/Converters/PrimitiveConverterLookup.tt, src/Nerdbank.MessagePack/Nerdbank.MessagePack.csproj, src/Nerdbank.MessagePack/SecureHash/CollisionResistantHasherLookup.cs, src/Nerdbank.MessagePack/SecureHash/CollisionResistantHasherLookup.tt, src/Nerdbank.MessagePack/SecureHash/SecureVisitor.cs, src/Nerdbank.MessagePack/SecureHash/StructuralVisitor.cs
This drops the test app size by 100KB across all OS's.
(We can only claim 100KB decrease on Windows in the pipeline file because the other two operating systems had grown 100KB without being notated, and this brings them back down to target size).
=> Allow trimming of unused secure hash functions

src/Nerdbank.MessagePack/Converters/DictionaryConverter`3.cs, src/Nerdbank.MessagePack/PolyfillExtensions.cs, test/Nerdbank.MessagePack.Tests/AsyncSerializationTests.cs
* Dictionary serialization now supports async.
* ImmutableDictionary *de*serialization now supports async.
Mutable dictionary deserialization already supported async, so this finishes off async support for all dictionary types.
Closes #521
=> Add comprehensive async serialization support for dictionaries

src/Nerdbank.MessagePack/StandardVisitor.cs, test/Nerdbank.MessagePack.Tests/OddShapeTests.cs
Instead of throwing a `KeyNotFoundException` which looks like an internal serializer bug, throw an exception with a message that explains exactly what's wrong with the target type and what the user can do about it.
=> Throw a more helpful exception when serializing certain invalid types

src/Nerdbank.MessagePack/Converters/PrimitiveConverters.cs
Big thanks to @T0PP1ng for discovering this bug and fixing in our predecessor library via https://github.com/MessagePack-CSharp/MessagePack-CSharp/pull/2225.
=> Fix `DateTimeOffset` serialization to avoid timezone skew

Directory.Packages.props, src/Nerdbank.MessagePack/SecureHash/SecureVisitor.cs, src/Nerdbank.MessagePack/SecureHash/StructuralVisitor.cs, src/Nerdbank.MessagePack/StandardVisitor.cs, test/Nerdbank.MessagePack.Tests/SharedTestCases.cs
Throw any time we're asked to serialize or compare object graphs that include delegates
=> Bump PolyType to 0.60.1

docfx/docs/migrating.md, src/Nerdbank.MessagePack/Converters/PrimitiveConverters.cs, src/Nerdbank.MessagePack/JsonSchemaContext.cs, src/Nerdbank.MessagePack/MessagePackCode.cs, src/Nerdbank.MessagePack/MessagePackReader.cs, src/Nerdbank.MessagePack/MessagePackSerializationException.cs, src/Nerdbank.MessagePack/MessagePackSerializer.GetSchema.cs, src/Nerdbank.MessagePack/MessagePackSerializer.cs, src/Nerdbank.MessagePack/OptionalConverters.cs, src/Nerdbank.MessagePack/PolyfillExtensions.cs, src/Nerdbank.MessagePack/ReferenceEqualityTracker.cs, src/Nerdbank.MessagePack/SerializationContext.cs, test/Nerdbank.MessagePack.Tests/BuiltInConverterTests.cs, test/Nerdbank.MessagePack.Tests/ConvertToJsonTests.cs, test/Nerdbank.MessagePack.Tests/MessagePackSerializerTestBase.cs, test/Nerdbank.MessagePack.Tests/OptionalConvertersTests.cs, test/Nerdbank.MessagePack.Tests/SharedTestCases.cs, version.json
- Future proof the design of library extension type codes
- Encode `Int128` and `UInt128` as Bnative integers if they fit, otherwise as a BE msgpack extension. Allow decoding a LE Bin for compatibility with MessagePack-CSharp.
- Write `BigInteger` as an ordinary integer if it fits, otherwise use an extension. Allow decoding a Bin for compatibility with MessagePack-CSharp.
- Encode `decimal` as a msgpack extension instead of as a string. Allow decoding a string for compatibility with MessagePack-CSharp.
- Switch binary Guid encoding over to a msgpack extension
- Document the encodings in the MessagePack-CSharp migration section.
Closes #579
Closes #574
=> Use custom msgpack extensions for .NET "primitive" types

.github/workflows/build.yml, src/Nerdbank.MessagePack/Converters/PrimitiveConverterLookup.cs, src/Nerdbank.MessagePack/Converters/PrimitiveConverterLookup.tt, test/Nerdbank.MessagePack.Tests/AssemblyLoadTests.cs
This avoids loading `System.Numerics` and `System.Drawing` during serialization of types that wouldn't require them.
Note that due to https://github.com/eiriktsarpalis/PolyType/issues/252, if either of those assemblies are included in *any* source generated type shapes, they'll be loaded anyway.
=> Avoid loading unneeded assemblies while looking up primitive converters

src/Nerdbank.MessagePack/Converters/PrimitiveConverters.cs, test/Nerdbank.MessagePack.Tests/BuiltInConverterTests.cs
This allows msgpack data serialized with the OldSpec to be deserialized.
=> Allow `byte[]` to be deserialized from a Str header

docfx/docs/custom-converters.md, docfx/docs/unions.md, src/Nerdbank.MessagePack/ConverterCache.cs, src/Nerdbank.MessagePack/MessagePackConverterAttribute.cs, src/Nerdbank.MessagePack/StandardVisitor.cs, test/Nerdbank.MessagePack.Tests/DerivedTypeTests.cs, test/Nerdbank.MessagePack.Tests/MessagePackSerializerTests.cs
- Add support for custom converters on dictionaries and enumerables.
- Have custom converters fit *inside* union cases in all but member-attributed scenarios.
- Add support for `[MessagePackConverter(Type)]` on parameters.
=> Refine custom converter support

docfx/docs/features.md, docfx/docs/unions.md, samples/cs/Unions.cs, src/Nerdbank.MessagePack/ConverterCache.cs, src/Nerdbank.MessagePack/Converters/ShapeBasedUnionConverter`1.cs, src/Nerdbank.MessagePack/DerivedTypeDuckTyping.cs, src/Nerdbank.MessagePack/JsonSchemaContext.cs, src/Nerdbank.MessagePack/MessagePackSerializer.cs, src/Nerdbank.MessagePack/StandardVisitor.cs, test/Nerdbank.MessagePack.Tests/DerivedTypeDuckTypingTests.cs
Duck typing allows for types like this:
```cs
[GenerateShape]
public abstract partial record Animal(string Name);
[GenerateShape]
public partial record Dog(string Name, int BarkVolume) : Animal(Name);
[GenerateShape]
public partial record Cat(string Name, int MeowPitch) : Animal(Name);
```
To be deserialized from msgpack data such as:
```json
{ "Name": "Rover", "BarkVolume": 10 }
{ "Name": "Whiskers", "MeowPitch": 13 }
```
Note the lack of type header information. Instead, the required properties that are present will disambiguate the type to be deserialized.
=> Add duck typed unions

src/Nerdbank.MessagePack/ConverterCache.cs, src/Nerdbank.MessagePack/ConverterResult.cs, src/Nerdbank.MessagePack/Converters/DelayedConverterFactory.cs, src/Nerdbank.MessagePack/JsonSchemaContext.cs, src/Nerdbank.MessagePack/MessagePackSerializer.cs, src/Nerdbank.MessagePack/PolyfillExtensions.cs, src/Nerdbank.MessagePack/ReferencePreservingVisitor.cs, src/Nerdbank.MessagePack/ResultExtensions.cs, src/Nerdbank.MessagePack/Result`2.cs, src/Nerdbank.MessagePack/SerializationContext.cs, src/Nerdbank.MessagePack/StandardVisitor.cs, src/Nerdbank.MessagePack/StreamingDeserializer`1.cs, src/Nerdbank.MessagePack/VisitorError.cs, test/Nerdbank.MessagePack.Tests/MessagePackSerializerTestBase.cs, test/Nerdbank.MessagePack.Tests/MessagePackSerializerTests.cs, test/Nerdbank.MessagePack.Tests/SerializationRejectsFunctionsTests.cs
We use new converter monads to allow representing success and failure cases, so that failure cases can be tracked and thrown or ignored by the visitor callers as appropriate. This allows us to completely avoid throwing exceptions until we know that we want to throw an observed one.
=> Ignore non-serializable types (e.g. delegates) buried in properties that we won't serialize

src/Nerdbank.MessagePack/Converters/PrimitivesAsObjectConverter.cs, test/Nerdbank.MessagePack.Tests/PrimitivesDerializationTests.cs, test/Nerdbank.MessagePack.Tests/PrimitivesDynamicDeserializationTests.cs
This allows serializing a `DateTime` with `DateTimeKind.Unspecified` to be serialized while typed as `object` (when `WithObjectConverter()` is used), respecting whatever default Kind is set using `WithAssumedDateTimeKind`.
=> Primitive object serializer respects `WithAssumedDateTimeKind`

src/Nerdbank.MessagePack/MessagePackAsyncWriter.cs, test/Nerdbank.MessagePack.Tests/MessagePackSerializerTestBase.cs
The `MessagePackAsyncWriter.CreateWriter()` method was unnecessarily calling `IBufferWriter<byte>.Advance(int)` on .NET Framework. But beyond being overhead, this line is somehow responsible for the following exception which comes up randomly in yielding async serialization scenarios:
```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
Pipe.Advance(Int32 bytes)
BufferMemoryWriter.Commit() line 86
MessagePackAsyncWriter.CreateWriter() line 44
<WriteAsync>d__12.MoveNext() line 113
```
I don't know why the old code was defective. I only know it shouldn't be necessary, and that its removal makes the exception go away. I've adjusted the tests to cover yielding async …
=> Remove unnecessary Commit() during async serialization
